### ISSUE TITLE
When will the code be released

### ISSUE THREAD

**Issue by amiltonwong** [Yang7879/3D-BoNet#1]
Hi, @Yang7879 ,

When will the code be released?
THX!

**Comment by sebastianPsm** [comment]
+1

**Comment by Yang7879** [comment]
Hi @amiltonwong @sebastianPsm Thanks for your interests. Will be available soon.

**Comment by daveredrum** [comment]
Really like this paper! Looking forward to the code so that we can get our hands on it and try it out :)

**Comment by masotrix** [comment]
Is it still going out? It is expected for important projects.

**Comment by kentaroy47** [comment]
+1

**Comment by FishWantToFly** [comment]
+1

**Comment by Yang7879** [comment]
Hi @amiltonwong @sebastianPsm @daveredrum @masotrix @kentaroy47, thank you for your interests and really sorry for my late response. The code is made available now.

**Comment by amiltonwong** [comment]
@Yang7879 , Many thanks!
