### ISSUE TITLE
KITTI dataset

### ISSUE THREAD

**Issue by iris0329** [Yang7879/3D-BoNet#2]
Hi, @Yang7879 

Thanks for sharing this amazing work, 
do you have some experience result on KITTI ?

**Comment by Yang7879** [comment]
Hi @iris0329 , thx for your interests, unfortunately, we haven't done experiments on KITTI yet.

**Comment by abhigoku10** [comment]
@iris0329 @Yang7879  thanks for sharing the source code , any plans of doing the experients on kitti or semanttic kitti  or can we train ourself on semanttic kitti dataset if so what is the modification changes have to be made

**Comment by iris0329** [comment]
Thank you ~

**Comment by iris0329** [comment]
Thank you ~
