### ISSUE TITLE
Cannot create a new submission on ScanNet Test Benchmark

### ISSUE THREAD

**Issue by jytime** [Yang7879/3D-BoNet#23]
Hi @Yang7879,

Thanks for your excellent work. I am trying to extend Bo-Net and now go well on the ScanNet eval dataset. However, when I try to check the performance on the test dataset, the ScanNet benchmark does not respond. 

I have successfully created an account and am trying to submit my 3D instance segmentation results. After filling the information required in the 'Create New Submission' page and clicking on the 'Save' button, the website always returns "This page isn't working; kaldir.vc.in.tum.de is currently unable to handle this request. Http Error 500".

I was wondering if you met this problem during submission. It would be great if any hint is available.

Best Regards,
Jianyuan

**Comment by Yang7879** [comment]
Hi @jytime , suppose your data format is correct (i mean generated from the scannet official script), that error might be from the server itself. I didn't have that error before (many months ago), and I suggest u contact the ScanNet team for a solution.

**Comment by jytime** [comment]
Thanks for your reply. I would send them an email. 

Best,
Jianyuan
