### ISSUE TITLE
Question regarding point mask prediction + class based labeling

### ISSUE THREAD

**Issue by lawrenceyan** [Yang7879/3D-BoNet#3]
Hi, I'm Lawrence. I'm an undergraduate student studying applied mathematics at UC Berkeley. I saw your paper posted on /r/machinelearning and found it super interesting! I'm trying to re-implement the network myself right now in order to try and improve my programming / machine learning implementation skills.

I was looking at the point mask prediction part of your model, and I was wondering if instead of doing a binary classification, you could add on an additional level of detail with a multi-class label assuming the existing data set had classified labels. 

I was thinking that this theoretically shouldn't have much effect on the loss since in the worst case, the classification should basically just degrade into the existing binary classification. But I'm finding that my loss shoots up dramatically when I try to implement it into the model. Is there something that I'm failing to account for here, that I should be thinking about or need to add in addition?

**Comment by lawrenceyan** [comment]
Resolved.

**Comment by Yang7879** [comment]
@lawrenceyan Thank you for your interests and the code is available now. Hope our previous discussion thru emails could be helpful for your work.
