### ISSUE TITLE
How do you download part of ScanNet for 3D instance segmentation?

### ISSUE THREAD

**Issue by DRosemei** [Yang7879/3D-BoNet#34]
@Yang7879 Thanks for your amaizng work, but I got trouble in downloading ScanNetv2 dataset. When I used the script "python2 download-scannet.py -o ScanNetDatav2/", it warned me that "WARNING: You are downloading the entire ScanNet v2 release which requires 1.2TB of space." I have limited space, so how do you download part of ScanNet for 3D instance segmentation?

**Comment by Yang7879** [comment]
hi @DRosemei , at the begining the script, you need to modify the list you need to download.

FILETYPES = ['.aggregation.json', '.sens', '.txt', '_vh_clean.ply', '_vh_clean_2.0.010000.segs.json', '_vh_clean_2.ply', '_vh_clean.segs.json', '_vh_clean.aggregation.json', '_vh_clean_2.labels.ply', '_2d-instance.zip', '_2d-instance-filt.zip', '_2d-label.zip', '_2d-label-filt.zip']
#####!!!!!!  change to the following
FILETYPES = ['.aggregation.json', '_vh_clean_2.0.010000.segs.json', '_vh_clean_2.ply', '_vh_clean.aggregation.json', '_vh_clean_2.labels.ply']

FILETYPES_TEST = ['.sens', '.txt', '_vh_clean.ply', '_vh_clean_2.ply']
#####!!!!!! change to the following
FILETYPES_TEST = ['_vh_clean_2.ply']

**Comment by DRosemei** [comment]
@Yang7879 Thanks for your help:)

**Comment by DRosemei** [comment]
Hi @Yang7879  Sorry to bother you once more. The speed of downloading this dataset is too small. It costed me 5 days to download noly aboout 200 scenes. Could you provide some links like Baidu Netdisk? Thank you in advance!
<img width="844" alt="1" src="https://user-images.githubusercontent.com/27892562/76932849-d87d8580-6926-11ea-8b1a-38cbd1ffc124.PNG">
<img width="852" alt="2" src="https://user-images.githubusercontent.com/27892562/76932894-ecc18280-6926-11ea-8101-3babdc48b515.PNG">

**Comment by bonbonjour** [comment]
@DRosemei Have you completed processing scannet database? the _vh_clean_2.ply is mesh file, I don't know how to get their xyzrgb attribute, can you please help me？

**Comment by DRosemei** [comment]
@bonbonjour Sorry, I haven't completed it yet cause I have some other things to do these days.
