### ISSUE TITLE
NYU dataset 

### ISSUE THREAD

**Issue by BenChenCh** [Yang7879/3D-BoNet#4]
Hi, @Yang7879

Thanks for sharing this amazing work,
Would you also release the code about  NYU dataset ?

**Comment by Yang7879** [comment]
Hi @BenChenCh, thanks for your interests. Unfortunately, we haven't done experiments on NYU dataset yet.

**Comment by BenChenCh** [comment]
Thanks for replying. Is it possible to use 3D-BoNet with nyu dataset  by  convertitng depth image to point cloud

**Comment by Yang7879** [comment]
@BenChenCh  It should be possible, but it may need some efforts to tune the network because the point clouds converted from depth images are usually partial and incomplete. The data statistics are quite different from S3DIS and ScanNet in which the point clouds are relatively more complete.
