### ISSUE TITLE
Questions on merging instances

### ISSUE THREAD

**Issue by tanghaotommy** [Yang7879/3D-BoNet#9]
Thanks for sharing the code and congratulations on your NeurIPS spotlight!!!

If I understand correctly, when testing, you still test on each block (1m*1m) and then merge? My question is: if one instance, e.g. long table that is 3m long, I would imagine that this instance can span two or more blocks. How do you merge the same instance from multiple blocks?

**Comment by Yang7879** [comment]
@tanghaotommy  We use the existing block merge algorithm introduced by SGPN. It takes into account both predicted semantic and instance labels when processing blocks. Basically, for two neighboring blocks, if two separate instances belong to the same category, it's more likely to merge them as a larger instance. You may check their paper for details.

**Comment by tanghaotommy** [comment]
Thanks a lot for the detail explanations!
